### ISSUE TITLE
输入用户名获取不到博客信息

### ISSUE THREAD

**Issue by is-ZYL** [chenhaoxiang/CSDNBlogExport#1]
错误代码如下：

`[INFO] 2018-09-03 11:39:47 [cn.chenhaoxiang.CSDNBlogExport.startGetBlogID(CSDNBlogExport.java:167)] -> 用户名:loveer0 [AWT-EventQueue-0] [chx]
[INFO] 2018-09-03 11:39:48 [us.codecraft.webmagic.Spider.run(Spider.java:306)] -> Spider blog.csdn.net started! [AWT-EventQueue-0] [chx]
[INFO] 2018-09-03 11:39:49 [us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:88)] -> downloading page success http://blog.csdn.net/loveer0 [pool-1-thread-1] [chx]
[INFO] 2018-09-03 11:39:49 [cn.chenhaoxiang.CSDNBlogExport.process(CSDNBlogExport.java:65)] -> 开始获取loveer0的博客文章ID... [pool-1-thread-1] [chx]
[ERROR] 2018-09-03 11:39:49 [us.codecraft.webmagic.Spider$1.run(Spider.java:324)] -> process request Request{url='http://blog.csdn.net/loveer0', method='null', extras=null, priority=0, headers={}, cookies={}} error [pool-1-thread-1] [chx]
java.lang.NullPointerException
	at cn.chenhaoxiang.CSDNBlogExport.process(CSDNBlogExport.java:94)
	at us.codecraft.webmagic.Spider.onDownloadSuccess(Spider.java:414)
	at us.codecraft.webmagic.Spider.processRequest(Spider.java:406)
	at us.codecraft.webmagic.Spider.access$000(Spider.java:61)
	at us.codecraft.webmagic.Spider$1.run(Spider.java:320)
	at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2018-09-03 11:39:49 [us.codecraft.webmagic.Spider.run(Spider.java:338)] -> Spider blog.csdn.net closed! 1 pages downloaded. [AWT-EventQueue-0] [chx]
[INFO] 2018-09-03 11:39:49 [cn.chenhaoxiang.CSDNBlogExport.startGetBlogID(CSDNBlogExport.java:176)] -> 本次查询的文章ID数量:0 [AWT-EventQueue-0] [chx]`

**Comment by chenhaoxiang** [comment]
你好，由于CSDN的新界面改版，但是我的代码中还是没有进行改版的。建议可以使用老主题试试。因为最近没有时间进行修改代码，非常抱歉，但是可以star，后期可能会针对新版本进行代码的导出更新

________________________________
chxpostbox@outlook.com

发件人： is-ZYL<mailto:notifications@github.com>
发送时间： 2018-09-03 11:43
收件人： chenhaoxiang/CSDNBlogExport<mailto:CSDNBlogExport@noreply.github.com>
抄送： Subscribed<mailto:subscribed@noreply.github.com>
主题： [chenhaoxiang/CSDNBlogExport] 输入用户名获取不到博客信息 (#1)

错误代码如下：

[INFO] 2018-09-03 11:39:47 [cn.chenhaoxiang.CSDNBlogExport.startGetBlogID(CSDNBlogExport.java:167)] -> 用户名:loveer0 [AWT-EventQueue-0] [chx] [INFO] 2018-09-03 11:39:48 [us.codecraft.webmagic.Spider.run(Spider.java:306)] -> Spider blog.csdn.net started! [AWT-EventQueue-0] [chx] [INFO] 2018-09-03 11:39:49 [us.codecraft.webmagic.downloader.HttpClientDownloader.download(HttpClientDownloader.java:88)] -> downloading page success http://blog.csdn.net/loveer0 [pool-1-thread-1] [chx] [INFO] 2018-09-03 11:39:49 [cn.chenhaoxiang.CSDNBlogExport.process(CSDNBlogExport.java:65)] -> 开始获取loveer0的博客文章ID... [pool-1-thread-1] [chx] [ERROR] 2018-09-03 11:39:49 [us.codecraft.webmagic.Spider$1.run(Spider.java:324)] -> process request Request{url='http://blog.csdn.net/loveer0', method='null', extras=null, priority=0, headers={}, cookies={}} error [pool-1-thread-1] [chx] java.lang.NullPointerException at cn.chenhaoxiang.CSDNBlogExport.process(CSDNBlogExport.java:94) at us.codecraft.webmagic.Spider.onDownloadSuccess(Spider.java:414) at us.codecraft.webmagic.Spider.processRequest(Spider.java:406) at us.codecraft.webmagic.Spider.access$000(Spider.java:61) at us.codecraft.webmagic.Spider$1.run(Spider.java:320) at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) [INFO] 2018-09-03 11:39:49 [us.codecraft.webmagic.Spider.run(Spider.java:338)] -> Spider blog.csdn.net closed! 1 pages downloaded. [AWT-EventQueue-0] [chx] [INFO] 2018-09-03 11:39:49 [cn.chenhaoxiang.CSDNBlogExport.startGetBlogID(CSDNBlogExport.java:176)] -> 本次查询的文章ID数量:0 [AWT-EventQueue-0] [chx]

**Comment by lijiaxiucai** [comment]
作者，你好，这个工具还会维护吗？
2019年2月28，下载源码测试的时候，依旧提示本次线程获取0篇文章...您的博客数量为0。
